Система управления репозиториями:
  Главный мастер - крутится в продакшен сборке локально
  Деплой - жестко порезанная версия, которая крутится на внешнем хосте
  Стейдж ветка - крутится в дев-версии. Если успешно собирается - отправляет на стейдж сблоки. 
    При сборке сначала пушит в главный мастер, потом обрезает оттуда под шейп деплоя


